### ISSUE TITLE
Could antlr4ng used in Mocha?

### ISSUE THREAD

**Issue by fdlsk2r** [mike-lischke/antlr4ng#23]
When i used antlr4ng in Mocha's tests, it will run into errors:
```
[...]/src/parser/ExprParser.ts:28
    public static readonly Colon = 14;
                           ^
Error [ERR_REQUIRE_ESM]: require() of ES Module [...]/node_modules/.pnpm/antlr4ng@2.0.4_antlr4ng-cli@1.0.7/node_modules/antlr4ng/dist/antlr4.mjs not supported.
Instead change the require of [...]/node_modules/.pnpm/antlr4ng@2.0.4_antlr4ng-cli@1.0.7/node_modules/antlr4ng/dist/antlr4.mjs to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> ([...]/src/parser/ExprParser.ts:28:28)
    at m._compile ([...]/node_modules/.pnpm/ts-node@8.10.2_typescript@4.9.5/node_modules/ts-node/dist/index.js:556:29)
    at require.extensions.<computed> [as .ts] ([...]/node_modules/.pnpm/ts-node@8.10.2_typescript@4.9.5/node_modules/ts-node/dist/index.js:558:16)
    at Object.<anonymous> ([...]/packages/expr/src/core/parse.ts:27:24)
    at m._compile ([...]/node_modules/.pnpm/ts-node@8.10.2_typescript@4.9.5/node_modules/ts-node/dist/index.js:556:29)
    at require.extensions.<computed> [as .ts] ([...]/node_modules/.pnpm/ts-node@8.10.2_typescript@4.9.5/node_modules/ts-node/dist/index.js:558:16)
    at Object.<anonymous> ([...]/packages/expr/tests/core.test.ts:3:17)
    at m._compile ([...]/node_modules/.pnpm/ts-node@8.10.2_typescript@4.9.5/node_modules/ts-node/dist/index.js:556:29)
    at require.extensions.<computed> [as .ts] ([...]/node_modules/.pnpm/ts-node@8.10.2_typescript@4.9.5/node_modules/ts-node/dist/index.js:558:16)
    at [...]/node_modules/.pnpm/mocha@6.2.3/node_modules/mocha/lib/mocha.js:334:36
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles ([...]/node_modules/.pnpm/mocha@6.2.3/node_modules/mocha/lib/mocha.js:331:14)
    ......
```

As I know, `Mocha` only support `CommonJS`, Does it means that we cannot use `antlr4ng` in UnitTests?

Thanks~

**Comment by mike-lischke** [comment]
FYI: the package now comes also with a CommonJS bundle, which should solve your problem without any extra tool.
